app:
  cluster:
    node:
      name: member-1
      host: localhost
      port: 10001
    members:
      - name: member-1
        host: localhost
        port: 10001
    storage-path: cluster-storage