version: "3.8"

services: 
  load-balancer:
    image: nginx:alpine
    ports: 
      - "9000:8080"
    volumes: 
      - "../nginx/lb.conf:/etc/nginx/conf.d/default.conf"
    networks: 
      - demo-spring-boot-atomix
  member-1:
    build: "../Dockerfile"
    image: demo-spring-boot-atomix:1.0
    container_name: member-1
    environment: 
      SERVER_PORT: 8080
    volumes: 
      - "./config/application-member-1.yaml:/app/application.yaml"
      - "demo-spring-boot-atomix-member-1:/app/cluster-storage"
    networks: 
      - demo-spring-boot-atomix
    depends_on: 
      - load-balancer

volumes: 
  demo-spring-boot-atomix-member-1:

networks:
  demo-spring-boot-atomix: